[build]
builder = "nixpacks"
workingDirectory = "backend"
buildCommand = "npm ci"

[deploy]
workingDirectory = "backend"
startCommand = "npm run start-simple"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/chromium/bin/chromium"
NODE_VERSION = "18.20.8"